export const aboutObjTwo ={
    lightBg:true,
    primary:false,
    imgStart:"start",
    lightTopLine:false,
    lightText:false,
    buttonLabel:"Learn more",
    description:"Our mission is centered on empowering communities through faith and service. We believe in making a meaningful difference by sharing our faith and extending a helping hand to those around us. With compassion as our guide and service as our commitment, we endeavor to uplift individuals and communities alike. Through our actions, we aim to inspire hope, foster unity, and create positive change. Together, we strive towards building a world where everyone feels supported, valued, and empowered to reach their fullest potential.",
    description1:"Join us in our journey towards spiritual enlightenment and growth. Discover the transformative power of faith.",
    lightTextDesc:false,
    headLine:"Learn About Us: ECI",
    topLine:"Evangelical Church of India",
    img: require('../../images/WhatsApp Image 2024-02-11 at 13.55.34_8a39b0e8 copy.jpg').default,
    alt:'Image',
    start:'true',
}
export const aboutObjImgTwo ={
    lightBg:true,
    primary:false,
    imgStart:"",
    lightTopLine:false,
    lightText:false,
    buttonLabel:"Learn more",
    description:"Empowering communities through faith and service has been our mission. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint earum, eos esse non error facilis ad, maiores eum quae vero libero voluptas! Reprehenderit sunt similique, quae quidem voluptatem odit natus.",
    description1:"Join us in our journey towards spiritual enlightenment and growth. Discover the transformative power of faith.",
    lightTextDesc:false,
    headLine:"Serving Communities with Faith and Service",
    topLine:"Evangelical Church of India",
    img: require('../../images//WhatsApp Image 2024-02-11 at 13.55.34_0976004d.jpg').default,
    alt:'Image',
    start:'true',
}