export const homeObjOne ={
    lightBg:false,
    primary:true,
    imgStart:"",
    lightTopLine:true,
    lightText:true,
    buttonLabel:"Prayer Request",
    description:"Our Hearts unite in praise Guided by His love, we find our ways Together we stand, in faith we raise",
    lightTextDesc:true,
    headLine:"I Can Do All This Through Him Who Gives Me Strength.",
    topLine:"Philippians 4:13",
    img: require('../../images/catholic church.png').default,
    alt:'Image',
    start:'',
}
export const homeObjTwo ={
    lightBg:true,
    primary:false,
    imgStart:"start",
    lightTopLine:false,
    lightText:false,
    buttonLabel:"Learn more",
    description:"Embrace the journey towards spiritual enlightenment and growth as we invite you to join us on a path. Together, we strive to cultivate a community rooted in love, compassion, and service, where every soul is valued and every heart finds solace.",
    description1:"Join us in our journey towards spiritual enlightenment and growth. Discover the transformative power of faith.",
    lightTextDesc:false,
    headLine:"Experience Spiritual Growth with ECI",
    topLine:"Evangelical Church of India",
    img: require('../../images/pic.jpg').default,
    alt:'Image',
    start:'true',
}
export const homeObjThree ={
    lightBg:false,
    primary:true,
    imgStart:"",
    lightTopLine:true,
    lightText:true,
    buttonLabel:"Learn more",
    description:"Discover how the Evangelical Church of India serves communities, embraces faith, and fosters growth for individuals.",
    lightTextDesc:true,
    headLine:"Empowering Lives through Faith",
    topLine:"WHY CHOOSE ECI",
    img: require('../../images/praying-people-in-church.jpg').default,
    alt:'Image',
    start:'',
}
export const homeObjFour ={
    lightBg:false,
    primary:true,
    imgStart:"start",
    lightTopLine:true,
    lightText:true,
    buttonLabel:"Get Started",
    description:"The teachings and support i've received from ECI have transformed my life - Michael Johnson",
    description2:"I have found profound guidance and support within the ECI community - Linda Patel",
    description3:"ECI's teachings have bought immense positivity into my life. I'm grateful to be part of ECI community - Rajesh Kumar",
    description4:"The sense of unity and compassion at ECI has helped me grow spiritually and personally. - Sarah Thomas",
    lightTextDesc:true,
    headLine:"What Our Members Say",
    topLine:"Testimonials",
    img: require('../../images/group-of-people.jpg').default,
    alt:'Image',
    start:'true',
}